# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date_of_request',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='installments',
            field=models.IntegerField(help_text='Amount to pay in monthly installments'),
        ),
    ]
